apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccit-dep2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ccit
  template:
    metadata:
      labels:
        app: ccit
    spec:
      containers:
      - name: cont-2
        image: cloudintelugu/ccitimage:v4
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "ccit v4"
---
apiVersion: v1
kind: Service
metadata:
  name: ccit-svc2
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: ccit
